config/routes.rb
SampleApp::Application.routes.draw do
  resources :users 
  resources :hotels do
    resources :comments
    resources :votes
  end
  resources :sessions, only: [:new, :create, :destroy]
  root  'hotels#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/listOfHotels', to: 'hotels#list_of_hotels', via: 'get'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
  validates :user_name, presence: true
  validates :body, presence: true
  validates :hotel_id, presence: true
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
belongs_to :user
has_many :comments, dependent: :destroy
has_many :votes, dependent: :destroy
scope :top5, -> {
    select("hotels.id, hotels.title, hotels.star_rating, hotels.breakfast,
     hotels.image, hotels.room_desc, hotels.price, hotels.address,count(votes) AS votes_count").
    joins(:votes).
    group("hotels.id, hotels.title, hotels.star_rating,
     hotels.breakfast, hotels.image, hotels.room_desc, hotels.price, hotels.address").
    order("votes_count DESC").
    limit(5)
}
#Hotel.top5
validates :title, presence: true, length: {minimum:2, maximum:30}
VALID_BREAK_REGEX = /\A+\d/
#validates :breakfast, presence: true, format: {with:VALID_BREAK_REGEX}
validates :star_rating, presence: true, format: {with: /\A+[1-5]/}
validates :room_desc, presence: true
validates :price, presence: true, format: {with:VALID_BREAK_REGEX}
validates :address, presence: true
validates :image, presence: true
mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :hotels, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :hotel
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def create
    @hotel = Hotel.find(params[:hotel_id])
    @comment = Comment.create(comment_params)
    @comment.hotel_id = @hotel.id
    @comment.user_name = current_user.name
    if @comment.save
      redirect_to hotel_path(@hotel)
    else
      redirect_to hotel_path(@hotel)
    end
  end

  def destroy
    @hotel = Hotel.find(params[:hotel_id])
    @comment = @hotel.comments.find(params[:id])
    @comment.destroy
    redirect_to hotel_path(@hotel)
  end
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def index
  	@hotel = Hotel.top5
  end
 
  def show
  	@hotel= Hotel.find(params[:id])     
  end

  def new
    @hotel = Hotel.new
  end

  def list_of_hotels
    @hotel = Hotel.all
  end

  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.user_id = current_user.id
    if @hotel.save
      @hotel.votes.create
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end
 
  def update
    @hotel = Hotel.find(params[:id])
 
    if @hotel.update(hotel_params)
      redirect_to current_user 
    else
      render 'edit'
    end
  end
 
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
 
    redirect_to current_user 
  end
 
  private
    def hotel_params
      params.require(:hotel).permit(:title, :star_rating, :breakfast, :room_desc, :price, :address, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
  else
    flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
  end
end

  def destroy
    sign_out
    redirect_to root_url
  end	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
	
  def show
    @user = User.find(params[:id])
    @hotel = @user.hotels.paginate(page: params[:page], per_page: 2)
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
    	@hotel = Hotel.find(params[:hotel_id])
    	@vote = Vote.create
    	@vote.hotel_id = @hotel.id
    	@vote.user_id = current_user.id
   	 	if @vote.save
      		redirect_to hotel_path(@hotel)
    	else
      redirect_to hotel_path(@hotel)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Rails Station"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 100 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/blocks/_preview.html.erb
<span class="content">
    <%= link_to hotel_path(hotel) do %> 
		<div class="div_preview_enrty" >
			<div class="div_preview_pic">
				<%= image_tag hotel.image.thumb.url %>
			</div>

			<div class="div_preview_text" >
				<div class="div_preview_title">
					<%= hotel.title %>
				</div>

				<div class="div_preview_decr">
					<p><%= hotel.room_desc %></p>
				</div>

				<div class="div_preview_icons">
					<div class="div_preview_likes">
				      <%= form_for([hotel, hotel.votes.build]) do |f| %>
				        <div class="fa fa-thumbs-up"></div>
				         &ndash; <%= hotel.votes.count %>    
				      <% end %>
					</div>
					<div class="div_preview_stars">
						<i class="fa fa-star" aria-hidden="true"></i>
						 &ndash; <%= hotel.star_rating %>
					</div>
					<div class="div_preview_food">
						<i class="fa fa-cutlery" aria-hidden="true"></i>
						 &ndash; <%= hotel.breakfast %>
					</div>
					<div class="div_preview_dollar">
						<i class="fa fa-usd" aria-hidden="true"></i>
						 &ndash; <%= hotel.price %>
				</div>
				</div>
			
			</div>
		</div>
	<% end %>
</span>

app/views/blocks/_show_hotel.html.erb
    <h1>
      <%= @hotel.title %>
    </h1>
    <hr />

    <div class="div_descr_1">
       <%= image_tag @hotel.image.thumb.url %>
    </div>

    <div class="div_descr_3">
        <h2><%= render 'vote_buttom' %></h2>
    </div>

    <div class="div_descr_6">
        <h2><i class="fa fa-star" aria-hidden="true"></i>
        &emsp;-&emsp;<%= @hotel.star_rating %> 
        </h2>
    </div>

    <div class="div_descr_4">
        <h2><i class="fa fa-usd" aria-hidden="true"></i>
        &emsp;-&emsp;<%= @hotel.price %><h2>
    </div>   

    <div class="div_descr_5">
        <h2><i class="fa fa-cutlery" aria-hidden="true"></i>
            &emsp;-&emsp;<%= @hotel.breakfast %></h2>
    </div>  

    <div class="div_descr_2">
        <br />
        <p><%= @hotel.room_desc %></p>
        <div>
            <br />
            <p><i>Address: &emsp; <%= @hotel.address %></i></p>
        </div>  
    </div>

    
   
    <div class="clear"></div>

app/views/hotels/_form.erb
<%= form_for @hotel, html: { multipart: true } do |f| %>

  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <div class="alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@hotel.errors.count, "error") %> prohibited
              this hotel from being saved:
            </h2>
            <ul>
              <% @hotel.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div> 
      </div>
  <% end %>

<div class="add_hotel_form">
    <!-- 1 -->
    <div class="row">
      <div class="span2">
        <%= f.label :title %>
      </div>
      <div class="span4">
          <%= f.text_field :title, placeholder: "Your hotel name"%>
      </div>
    </div>

    <!-- 2 -->

    <div class="row">
      <div class="span2">
        <%= f.label :star_rating %>
      </div>
      <div class="span4">
        <%= f.select(:star_rating, options_for_select([['1', '1'], 
                          ['2', '2'],['3', '3'],['4', '4'],['5', '5']])) %>
      </div>
    </div>

    <!-- 3 -->
    <div class="row">
      <div class="span2">
        <%= f.label :breakfast %>
      </div>
      <div class="span4">
        <%= f.select(:breakfast, options_for_select([['yes', 'yes'], 
                              ['no', 'no']],{ include_blank: true }))  %>
      </div>
    </div>

    <!-- 4 -->
    <div class="row">
      <div class="span2">
        <%= f.label :room_desc %>
      </div>
      <div class="span4">
        <%= f.text_area :room_desc, placeholder: "Tell about your hotel" %>
      </div>
    </div>

    <!-- 5 -->
    <div class="row">
      <div class="span2">
        <%= f.label :price %>
      </div>
      <div class="span4">
        <%= f.text_field :price, placeholder: "Amount" %>
      </div>
    </div>

    <!-- 6 -->
    <div class="row">
      <div class="span2">
        <%= f.label :address %>
      </div>
      <div class="span4">
        <%= f.text_field :address, placeholder: "Tell your hotel address" %>
      </div>
    </div>

    <!-- 7 -->
    <div class="row">
      <div class="span2"><%= f.label :image %></div>
      <div class="span1">
        <div class="field">
          <label class="btn btn-info btn-block ">
            <div hidden><%= f.file_field :image %></div>
            <i class="fa fa-upload" aria-hidden="true"></i>
          </label>
        </div>
      </div>
    </div>


    <div class="row">
        <div class="span2 offset4 field">
          <!-- <%= f.submit %> -->
          <button class="btn btn-large" onclick="$(this).closest('form').submit()">Submit</button>
        </div>
    </div>
</div>


<div class="add_hotel_pic">
  <%= image_tag("add_hotel_pic.jpg", :alt => "add_hotel_pic") %>
</div>


<% end %>

app/views/hotels/_vote_buttom.html.erb
<% if signed_in? %>
  <% if @hotel.votes.exists?(:user_id => current_user.id) || @hotel.user_id == current_user.id %>
     <!-- <%= pluralize(@hotel.votes.count, "vote") %> -->
     <!-- <i class="fa fa-thumbs-o-up" aria-hidden="true"></i> -->
     <i class="fa fa-thumbs-up" aria-hidden="true"></i>
     &emsp;-&emsp;<%= @hotel.votes.count %>
     <% else %>

      <%= form_for([@hotel, @hotel.votes.build]) do |f| %>
        <div class="fa fa-thumbs-o-up" onclick="$(this).closest('form').submit()" 
                                  style="cursor: pointer;"></div>
        &emsp;-&emsp;<%= @hotel.votes.count %>
     <% end %>
  <% end %>
  <% else %>
      <%= form_for([@hotel, @hotel.votes.build]) do |f| %>
        <div class="fa fa-thumbs-up"></div>
        &emsp;-&emsp;<%= @hotel.votes.count %>    
  <% end %>
<% end %>

app/views/hotels/edit.html.erb
<% if signed_in? && @hotel.user_id == current_user.id %>
<h1>Edit Hotel</h1>
<div class="center container hero-unit">
	<%= render 'form' %>
</div>
<%= link_to '', current_user, class: "go_back_btn fa fa-arrow-left fa-2x" %>
<% end %>

app/views/hotels/index.html.erb
<% provide(:title, '') %>
<div class="main_pic container-fluid">
    <br /><br /><br /><br />
    <div class="greeting_text" hidden>
        <h1 class="greeting_text">Find the lowest price on the right hotel for you</h1>
    </div>
    <div class="slogan_text" style="font-family: 'Open Sans', sans-serif;" hidden>
        <center><h2><strong> 
        'Hotel App' is the only hotel site that sends special investigators to visit, 
        photograph, review, and rate each hotel. We inspect in-person — just like your 
        mother-in-law.
        </strong></h2></center>
    </div>
</div>

<div class="center container hero-unit">
   	<h1>TOP 5 hotels</h1>
	<hr />
	<% @hotel.each do |hotel| %>

		<%= render :partial => 'blocks/preview', 
					:locals => {:hotel => hotel} %>
	<% end %>
</div>

app/views/hotels/list_of_hotels.html.erb
<% provide(:title, '') %>
<div class="main_pic container-fluid">
    <br /><br /><br /><br />
    <div class="greeting_text" hidden>
        <h1 class="greeting_text">Find the lowest price on the right hotel for you</h1>
    </div>
    <div class="slogan_text" style="font-family: 'Open Sans', sans-serif;" hidden>
        <center><h2><strong> 
        'Hotel App' is the only hotel site that sends special investigators to visit, 
        photograph, review, and rate each hotel. We inspect in-person — just like your 
        mother-in-law.
        </strong></h2></center>
    </div>
</div>
<div class="container center hero-unit">
    <center>
    <h1>List of hotels</h1>
	<hr />
        <% @hotel.each do |hotel| %>


        <%= render :partial => 'blocks/preview', 
                    :locals => {:hotel => hotel} %>
    <% end %>
    </center>
</div>

app/views/hotels/new.html.erb
<br />
<div class="add_form container hero-unit">
    <%= render 'form' %>
</div>
<%= link_to '', current_user, class: "go_back_btn fa fa-arrow-left fa-2x" %>

app/views/hotels/show.html.erb
<div class="container hero-unit">
  <%= render 'blocks/show_hotel' %>
  <br />
  <hr />
<h1 style="text-align: left;">Comments:</h1>
<div class="comment">
  <% @hotel.comments.each do |comment| %> 
    
    <p>
      <div class="row">
        <div class="span2 text_align_right">
          <strong><%= comment.user_name %>:</strong> 
        </div>
        <div class="span9" style="text-align: justify;">
          <%= comment.body %>
        </div>
        <div class="span1">
            <% if signed_in? && @hotel.user_id == current_user.id %>
              <div class="center">
                <%= link_to '', [comment.hotel, comment],
                          method: :delete,
                          data: { confirm: 'Are you sure?' }, 
                          class: "fa fa-ban fa-lg delete_btn"%>
              </div>
            <% end %>
        </div>
      </div>
    </p>
  <% end %>
</div>
<br />
<hr />

<% if signed_in? %> 
  <h2 style="text-align: left;">Add a comment:</h2>
  <%= form_for([@hotel, @hotel.comments.build]) do |f| %>
   <p>
     <%= f.text_area :body %>
   </p>
   <div class="pull-right">
     <button class="btn btn-info btn-large" id="add_comment_btn" onclick="">Submit</button>
   </div>
  <% end %>
  <% else %>
  </br>
  <p>
    <h2>You should sign up to create a comment</h2>
  </p>
<% end %>
<%= link_to '', root_path, class: "go_back_btn fa fa-arrow-left fa-2x" %>
</div> 


<script type="text/javascript">
$("button").click(function(){
    $.ajax({url: "show.html.erb", success: function(result){
        $(".comment").html(result);
    }});
});
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Simple web-application for hotel rating</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-collapse" id="top_menu"
role="navigation">
  <div class="navbar navbar-custom">
    <div class="container navbar-custom">
      <%= link_to image_tag('rs_logo.png', width: 37) + "Rails Station", root_path, id: "logo" %>

      <nav>
        <ul class="nav pull-right" id="nav_refs">
          <li><%= link_to "Main board", root_path, { :class=>"nav_links" } %></li>
          <li><%= link_to "List of hotels", listOfHotels_path, { :class=>"nav_links" } %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle nav_links" data-toggle="dropdown">
                Account <b class="caret" style="caret-color: #fff;"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user, { :class=>"nav_links" } %></li>
                <li><%= link_to "Add hotel", '/hotels/new', { :class=>"nav_links" } %></li>
                <li><%= link_to "Settings", edit_user_path(current_user), { :class=>"nav_links" }  %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, class: "nav_links", method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path, { :class=>"nav_links" } %></li>
            <li><%= link_to "Sign up now!", signup_path, { :class=>"nav_links" } %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <link rel="stylesheet" media="all" href="vendor/assets/stylesheets/animate.css">
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script>new WOW().init();</script>
  </head>
  <body class="root_body bg-fluid">
    <%= render 'layouts/header' %>
    <div class="content-fluid">
      
      <a href="#" id="go_top_btn"><i class="fa fa-arrow-circle-o-up fa-3x"></i></a>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>


 

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_for_user.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert" id="error_explanation">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
      <ul id="error_explanation">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  ***Where must be detailed information about application***
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  ***Where must be contact information***
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  ***Where must be some help-info about application***
</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% if signed_in? && @user.id == current_user.id %>
<h1>Update your profile</h1>

<div class="hero-unit container">
  <div class="row">

    <div class="span5 offset1">
      
      <%= image_tag("user_edit.png", :alt => "user_edit") %>

    </div>

    <div class="span4 offset1">
    
      <%= form_for(@user) do |f| %>

        <%= render 'shared/error_messages_for_user' %>

        <!-- <%= gravatar_for @user %> -->
        <a class="fa fa-picture-o fa-5x" href="http://gravatar.com/emails"
                  style="text-decoration: none"></a>
        
        <br />

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      <% end %>

    </div>

  </div>
</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="container container_form hero-unit">
  <div class="row">
    <div class="span3 offset1" style="float: left;">
      <%= image_tag("new_user.png", :alt => "sign_up") %>
    </div>
    <div class="span3 offset1" style="font-family: FontAwesome;">
      
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <!-- <i class="fa fa-user" aria-hidden="true"></i> -->
        <%= f.text_field :name, placeholder: "Name"%>

        <!-- <i class="fa fa-envelope" aria-hidden="true"></i> -->
        <%= f.text_field :email, placeholder: "E-mail" %>

        <!-- <i class="fa fa-unlock-alt" aria-hidden="true"></i> -->
        <%= f.password_field :password, placeholder: "Password" %>

        <!-- <i class="fa fa-unlock-alt" aria-hidden="true"></i> -->
        <%= f.password_field :password_confirmation, placeholder: "Confirmation" %>

        <%= f.submit "Create my account", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>	

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row container center hero-unit">
  <aside class="span12">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <% if @user.hotels.any? %>
      <% @hotel.each do |hotel| %>
      <hr />
        <%= render :partial => 'blocks/preview', 
                    :locals => {:hotel => hotel} %>
        <div class="text_align_left">
          &nbsp; &nbsp;

          <div class="btn-group btn-group-large">
            <%= link_to '', edit_hotel_path(hotel), class: "btn btn-warning btn-large fa fa-pencil-square-o fa-5x" %>
            <%= link_to '', hotel_path(hotel), class: "btn btn-danger btn-large fa fa-trash fa-5x",
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
          </div>
        

          
          
        </div>
      <% end %>
    <%= will_paginate @hotel %>
  <% end %>
</div>